const { onCall, HttpsError } = require("firebase-functions/v2/https");
const { defineSecret, defineString } = require("firebase-functions/params");
const { initializeApp } = require("firebase-admin/app");
const { getFirestore, FieldValue, Timestamp } = require("firebase-admin/firestore");
const { getAuth } = require("firebase-admin/auth");
const crypto = require("crypto");
const nodemailer = require("nodemailer");
initializeApp(); const db=getFirestore(),auth=getAuth();
const SMTP_PASSWORD=defineSecret("SMTP_PASSWORD"),SMTP_HOST=defineString("SMTP_HOST"),SMTP_PORT=defineString("SMTP_PORT",{default:"587"}),SMTP_SECURE=defineString("SMTP_SECURE",{default:"false"}),SMTP_USER=defineString("SMTP_USER"),SMTP_FROM=defineString("SMTP_FROM");
const ALLOWED_COLLECTIONS=new Set(["promotores","assistencia"]),CODE_TTL_MS=10*60*1000,MAX_ATTEMPTS=5;
async function requireAdmin(request){if(!request.auth?.uid)throw new HttpsError("unauthenticated","Faça login novamente.");const s=await db.doc(`administradores/${request.auth.uid}`).get();if(!s.exists||s.data()?.ativo!==true)throw new HttpsError("permission-denied","Conta sem permissão administrativa.");return{uid:request.auth.uid,...s.data()}}
function validateTarget(c,id){if(!ALLOWED_COLLECTIONS.has(c))throw new HttpsError("invalid-argument","Equipe inválida.");if(!id||typeof id!=="string")throw new HttpsError("invalid-argument","Profissional inválido.")}
const normalizeEmail=e=>String(e||"").trim().toLowerCase();
function hashCode(id,code,salt){return crypto.createHash("sha256").update(`${id}:${code}:${salt}`).digest("hex")}
function maskEmail(email){const[l,d]=String(email||"").split("@");return l&&d?l.slice(0,Math.min(2,l.length))+"•••@"+d:"e-mail cadastrado"}
function mailTransport(){return nodemailer.createTransport({host:SMTP_HOST.value(),port:Number(SMTP_PORT.value()),secure:SMTP_SECURE.value()==="true",auth:{user:SMTP_USER.value(),pass:SMTP_PASSWORD.value()}})}
exports.createTeamMember=onCall(async request=>{const admin=await requireAdmin(request);const d=request.data||{},collectionName=d.collection;validateTarget(collectionName,"new");const nome=String(d.nome||"").trim(),email=normalizeEmail(d.email),password=String(d.password||"");if(nome.length<2)throw new HttpsError("invalid-argument","Informe o nome completo.");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new HttpsError("invalid-argument","E-mail inválido.");if(password.length<6)throw new HttpsError("invalid-argument","A senha inicial deve ter pelo menos 6 caracteres.");const existing=await Promise.all([db.collection("promotores").where("email","==",email).limit(1).get(),db.collection("assistencia").where("email","==",email).limit(1).get()]);if(existing.some(s=>!s.empty))throw new HttpsError("already-exists","Já existe um membro com este e-mail.");let user;try{user=await auth.createUser({email,password,displayName:nome,emailVerified:false,disabled:false});const ref=db.collection(collectionName).doc();await ref.set({nome,email,telefone:String(d.telefone||"").trim(),cargo:String(d.cargo||"").trim()||(collectionName==="promotores"?"Promotor Técnico":"Assistente Técnico"),ativo:true,permissoes:{acessoApp:d.permissoes?.acessoApp!==false,agendarVisitas:d.permissoes?.agendarVisitas!==false,cadastrarClientes:d.permissoes?.cadastrarClientes!==false,finalizarVisitas:d.permissoes?.finalizarVisitas!==false,verHistorico:d.permissoes?.verHistorico!==false},authUid:user.uid,criadoEm:FieldValue.serverTimestamp(),criadoPor:admin.uid,atualizadoEm:FieldValue.serverTimestamp()});return{success:true,memberId:ref.id,authUid:user.uid}}catch(error){if(user?.uid)await auth.deleteUser(user.uid).catch(()=>{});if(error.code==="auth/email-already-exists")throw new HttpsError("already-exists","Este e-mail já possui uma conta de acesso.");throw error}});
exports.requestTeamMemberDeletion=onCall({secrets:[SMTP_PASSWORD]},async request=>{const admin=await requireAdmin(request),{collection:collectionName,memberId}=request.data||{};validateTarget(collectionName,memberId);const ref=db.doc(`${collectionName}/${memberId}`),snap=await ref.get();if(!snap.exists)throw new HttpsError("not-found","Profissional não encontrado.");const email=normalizeEmail(snap.data()?.email);if(!email)throw new HttpsError("failed-precondition","Este profissional não possui e-mail cadastrado.");const req=db.collection("exclusoes_usuario").doc(),code=String(crypto.randomInt(100000,1000000)),salt=crypto.randomBytes(16).toString("hex");await req.set({collection:collectionName,memberId,email,codeHash:hashCode(req.id,code,salt),salt,expiresAt:Timestamp.fromMillis(Date.now()+CODE_TTL_MS),requestedBy:admin.uid,requestedAt:FieldValue.serverTimestamp(),status:"pendente",attempts:0});await mailTransport().sendMail({from:SMTP_FROM.value(),to:email,subject:"Código de confirmação — exclusão de acesso Advance Check",text:`Código de confirmação: ${code}\nO código expira em 10 minutos.`,html:`<div style="font-family:Arial,sans-serif"><p>Foi solicitada a exclusão do seu acesso ao <strong>Advance Check</strong>.</p><p style="font-size:28px;font-weight:700;letter-spacing:6px">${code}</p><p>O código expira em 10 minutos.</p></div>`});return{requestId:req.id,maskedEmail:maskEmail(email),expiresInSeconds:600}});
exports.confirmTeamMemberDeletion=onCall(async request=>{const admin=await requireAdmin(request),{requestId,code}=request.data||{};if(!requestId||!/^\d{6}$/.test(String(code||"")))throw new HttpsError("invalid-argument","Código inválido.");const req=db.doc(`exclusoes_usuario/${requestId}`),s=await req.get();if(!s.exists)throw new HttpsError("not-found","Solicitação não encontrada.");const d=s.data();if(d.requestedBy!==admin.uid)throw new HttpsError("permission-denied","Confirmação de outro administrador.");if(d.status!=="pendente")throw new HttpsError("failed-precondition","Solicitação encerrada.");if(d.expiresAt?.toMillis()<Date.now()){await req.update({status:"expirado"});throw new HttpsError("deadline-exceeded","O código expirou.")}if((d.attempts||0)>=MAX_ATTEMPTS)throw new HttpsError("resource-exhausted","Limite de tentativas excedido.");const expected=Buffer.from(d.codeHash,"hex"),actual=Buffer.from(hashCode(requestId,String(code),d.salt),"hex");if(expected.length!==actual.length||!crypto.timingSafeEqual(expected,actual)){await req.update({attempts:FieldValue.increment(1)});throw new HttpsError("permission-denied","Código incorreto.")}const memberRef=db.doc(`${d.collection}/${d.memberId}`),memberSnap=await memberRef.get();if(!memberSnap.exists)throw new HttpsError("not-found","Profissional já removido.");const profile=memberSnap.data()||{};try{const u=profile.authUid?await auth.getUser(profile.authUid):await auth.getUserByEmail(d.email);await auth.deleteUser(u.uid)}catch(e){if(e.code!=="auth/user-not-found")throw e}const archive=db.collection("usuarios_excluidos").doc(`${d.collection}_${d.memberId}_${Date.now()}`),batch=db.batch();batch.set(archive,{colecaoOrigem:d.collection,memberId:d.memberId,perfil:profile,excluidoEm:FieldValue.serverTimestamp(),excluidoPor:admin.uid});batch.delete(memberRef);batch.update(req,{status:"concluido",confirmedAt:FieldValue.serverTimestamp()});await batch.commit();return{success:true}});
exports.updateTeamMemberEmail=onCall(async request=>{const admin=await requireAdmin(request),{collection:collectionName,memberId,newEmail}=request.data||{};validateTarget(collectionName,memberId);const email=normalizeEmail(newEmail);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new HttpsError("invalid-argument","E-mail inválido.");const ref=db.doc(`${collectionName}/${memberId}`),snap=await ref.get();if(!snap.exists)throw new HttpsError("not-found","Profissional não encontrado.");const data=snap.data()||{},old=normalizeEmail(data.email);if(old!==email){try{const u=data.authUid?await auth.getUser(data.authUid):await auth.getUserByEmail(old);await auth.updateUser(u.uid,{email})}catch(e){if(e.code!=="auth/user-not-found")throw e}}await ref.update({email,atualizadoEm:FieldValue.serverTimestamp(),atualizadoPor:admin.uid});return{success:true,email}});